### ISSUE TITLE
MySQL connection times out after a while

### ISSUE THREAD

**Issue by gargmegham** [gargmegham/MedicalGPT#9]
```
An exception was raised while handling an update
<pre>update = {
  "update_id": 831467649,
  "message": {
    "chat": {
      "id": 109165723,
      "type": "private",
      "last_name": "Ashrafian",
      "first_name": "Azim",
      "username": "AzimA77"
    },
    "text": "/new",
    "group_chat_created": false,
    "entities": [
      {
        "length": 4,
        "type": "bot_command",
        "offset": 0
      }
    ],
    "message_id": 2333,
    "delete_chat_photo": false,
    "date": 1684095598,
    "supergroup_chat_created": false,
    "channel_chat_created": false,
    "from": {
      "is_bot": false,
      "username": "AzimA77",
      "first_name": "Azim",
      "last_name": "Ashrafian",
      "id": 109165723,
      "language_code": "en"
    }
  }
}</pre>

<pre>Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 763, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (TimeoutError(110, 'Connection timed out'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1115, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/code/bot/handlers/commands.py", line 62, in new_dialog_handle
    mysql_db.set_attribute(user_id, "last_interaction", datetime.now())
  File "/code/bot/mysql.py", line 122, in set_attribute
    session.query(model).filter_by(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3284, in update
    self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1524, in orm_execute_statement
    return super().orm_execute_statement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 763, in _write_bytes
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (TimeoutError(110, 'Connection timed out'))")
[SQL: UPDATE user SET last_interaction=%(last_interaction)s WHERE user.user_id = %(user_id_1)s]
[parameters: {'last_interaction': datetime.datetime(2023, 5, 14, 20, 19, 59, 115670), 'user_id_1': '109165723'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
</pre>
```

**Comment by gargmegham** [comment]
https://github.com/gargmegham/MedicalGPT/pull/10
